import React, { useState } from 'react';
import { Card, Button, Select, Typography, Form, Input, Upload, DatePicker, message, Row, Col, Space, Image, Tag } from 'antd';
import { EditOutlined, SendOutlined, PlusOutlined, EyeOutlined, CalendarOutlined, LinkOutlined } from '@ant-design/icons';
import { NNVN_CATEGORIES } from '../../../services/crawlerService';
import { createPost } from '../../../services/autoPostService';
import moment from 'moment';

const { Title, Text, Paragraph } = Typography;
const { Option } = Select;
const { TextArea } = Input;

const AdminPostCreator = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [previewData, setPreviewData] = useState(null);
  const [imageUrl, setImageUrl] = useState('');

  const categories = { ...NNVN_CATEGORIES, 'tin-tuc': 'Tin tức', 'khac': 'Khác' };

  const handlePreview = () => {
    form.validateFields().then(values => {
      setPreviewData({ ...values, category: categories[values.category] || values.category, source: values.source || 'Admin tạo thủ công', publishedAt: values.publishedAt ? values.publishedAt.toDate() : new Date() });
    }).catch(() => message.error('Vui lòng điền đầy đủ thông tin'));
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);
      message.loading('Đang tạo bài viết...');
      await createPost({ ...values, category: categories[values.category] || values.category, source: values.source || 'Admin tạo thủ công', isAutoGenerated: false, publishedAt: values.publishedAt ? values.publishedAt.toDate() : new Date(), scrapedAt: new Date() });
      message.destroy();
      message.success('Đã tạo bài viết thành công!');
      form.resetFields();
      setImageUrl('');
      setPreviewData(null);
    } catch (error) {
      message.destroy();
      message.error('Lỗi: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card title={<><EditOutlined /> Tạo bài viết thủ công</>}>
        <Form form={form} layout="vertical" initialValues={{ category: 'nong-nghiep', source: 'Khuyến nông', publishedAt: moment() }}>
          <Row gutter={16}>
            <Col xs={24} lg={16}>
              <Form.Item label="Tiêu đề" name="title" rules={[{ required: true }]}><Input /></Form.Item>
              <Form.Item label="Nội dung" name="content" rules={[{ required: true }]}><TextArea rows={6} showCount maxLength={2000} /></Form.Item>
              <Row gutter={16}>
                <Col span={12}><Form.Item label="Danh mục" name="category" rules={[{ required: true }]}><Select>{Object.entries(categories).map(([k, v]) => <Option key={k} value={k}>{v}</Option>)}</Select></Form.Item></Col>
                <Col span={12}><Form.Item label="Nguồn" name="source"><Input /></Form.Item></Col>
              </Row>
              <Row gutter={16}>
                <Col span={12}><Form.Item label="Thời gian" name="publishedAt"><DatePicker showTime style={{ width: '100%' }} /></Form.Item></Col>
                <Col span={12}><Form.Item label="Link gốc" name="url"><Input /></Form.Item></Col>
              </Row>
            </Col>
            <Col xs={24} lg={8}>
              <Form.Item label="Hình ảnh">
                <Input placeholder="URL hình ảnh" value={imageUrl} onChange={(e) => { setImageUrl(e.target.value); form.setFieldsValue({ imageUrl: e.target.value }); }} />
                <div className="mt-2 border-dashed border-2 rounded-lg p-2 flex justify-center">
                  {imageUrl ? <Image src={imageUrl} height={150} /> : <div className="text-gray-400">Xem trước ảnh</div>}
                </div>
              </Form.Item>
            </Col>
          </Row>
          <Space className="mt-4">
            <Button icon={<EyeOutlined />} onClick={handlePreview} size="large">Xem trước</Button>
            <Button type="primary" icon={<SendOutlined />} onClick={handleSubmit} loading={loading} size="large" className="bg-[#795548] border-[#795548]">Đăng bài</Button>
          </Space>
        </Form>
      </Card>
      {previewData && (
        <Card title="Xem trước bài viết">
          <Title level={4}>{previewData.title}</Title>
          <Space className="mb-2"><Tag color="blue">{previewData.category}</Tag><Tag color="green">{previewData.source}</Tag></Space>
          <Paragraph className="text-gray-700">{previewData.content}</Paragraph>
        </Card>
      )}
    </div>
  );
};

export default AdminPostCreator;