import { db } from '../firebase/config';
import { collection, addDoc, query, where, getDocs, serverTimestamp } from 'firebase/firestore';
import { scrapeNNVNNews } from './crawlerService';

// Kiểm tra bài viết đã tồn tại dựa trên tiêu đề
export const checkPostExists = async (title) => {
  try {
    const postsRef = collection(db, 'posts');
    const q = query(postsRef, where('title', '==', title));
    const querySnapshot = await getDocs(q);
    return !querySnapshot.empty;
  } catch (error) {
    console.error('Error checking post exists:', error);
    return false;
  }
};

// Đăng bài viết mới vào Firebase
export const createPost = async (article) => {
  try {
    const postData = {
      title: article.title,
      content: article.content,
      category: article.category || 'Tin tức',
      authorId: 'auto-bot',
      authorName: 'Tin tức nông nghiệp',
      authorAvatar: 'https://ui-avatars.com/api/?name=TT&background=4CAF50&color=fff&size=128&font-size=0.6',
      authorReputation: 100,
      source: article.source || 'NNVN',
      imageUrl: article.imageUrl || null,
      images: article.imageUrl ? [article.imageUrl] : [],
      url: article.url || null,
      createdAt: serverTimestamp(),
      likes: 0,
      comments: 0,
      isAutoGenerated: true
    };

    const docRef = await addDoc(collection(db, 'posts'), postData);
    console.log('✅ Post created with ID:', docRef.id);
    return docRef.id;
  } catch (error) {
    console.error('❌ Error creating post:', error);
    throw error;
  }
};

// Cào và đăng bài tự động
export const scrapeAndPost = async (category = null, maxResults = 10) => {
  try {
    console.log('🤖 Starting auto scrape and post...');
    
    // Cào tin tức từ NNVN
    const articles = await scrapeNNVNNews(category, maxResults);
    console.log(`📰 Scraped ${articles.length} articles`);
    
    const results = {
      total: articles.length,
      posted: 0,
      skipped: 0,
      errors: 0
    };
    
    for (const article of articles) {
      try {
        // Kiểm tra bài viết đã tồn tại chưa
        const exists = await checkPostExists(article.title);
        
        if (exists) {
          console.log(`⏭️ Skipped: "${article.title}" (already exists)`);
          results.skipped++;
          continue;
        }
        
        // Đăng bài mới
        await createPost(article);
        console.log(`✅ Posted: "${article.title}"`);
        results.posted++;
        
        // Delay để tránh spam
        await new Promise(resolve => setTimeout(resolve, 1000));
        
      } catch (error) {
        console.error(`❌ Error posting "${article.title}":`, error);
        results.errors++;
      }
    }
    
    console.log('🎯 Auto post results:', results);
    return results;
    
  } catch (error) {
    console.error('❌ Error in scrapeAndPost:', error);
    throw error;
  }
};

export default {
  checkPostExists,
  createPost,
  scrapeAndPost
};