import React, { useState } from 'react';
import { 
  Card, 
  Button, 
  Select, 
  Typography, 
  Form,
  Input,
  Upload,
  DatePicker,
  message,
  Row,
  Col,
  Space,
  Image,
  Tag
} from 'antd';
import { 
  EditOutlined, 
  SendOutlined,
  PlusOutlined,
  EyeOutlined,
  CalendarOutlined,
  LinkOutlined
} from '@ant-design/icons';
import { NNVN_CATEGORIES } from '../services/crawlerService';
import { createPost } from '../services/autoPostService';
import moment from 'moment';

const { Title, Text, Paragraph } = Typography;
const { Option } = Select;
const { TextArea } = Input;

const AdminPostCreator = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [previewData, setPreviewData] = useState(null);
  const [imageUrl, setImageUrl] = useState('');

  // Danh mục mặc định giống bot
  const categories = {
    ...NNVN_CATEGORIES,
    'tin-tuc': 'Tin tức',
    'khac': 'Khác'
  };

  // Xử lý upload ảnh
  const handleImageChange = (info) => {
    if (info.file.status === 'uploading') {
      return;
    }
    if (info.file.status === 'done') {
      // Giả lập URL ảnh (thực tế cần upload lên server)
      const url = URL.createObjectURL(info.file.originFileObj);
      setImageUrl(url);
      form.setFieldsValue({ imageUrl: url });
    }
  };

  // Xử lý nhập URL ảnh
  const handleImageUrlChange = (e) => {
    const url = e.target.value;
    setImageUrl(url);
    form.setFieldsValue({ imageUrl: url });
  };

  // Xem trước bài viết
  const handlePreview = () => {
    form.validateFields().then(values => {
      const previewArticle = {
        title: values.title,
        content: values.content,
        category: categories[values.category] || values.category,
        source: values.source || 'Admin tạo thủ công',
        imageUrl: values.imageUrl,
        url: values.url,
        publishedAt: values.publishedAt ? values.publishedAt.toDate() : new Date(),
        scrapedAt: new Date()
      };
      setPreviewData(previewArticle);
    }).catch(errorInfo => {
      message.error('Vui lòng điền đầy đủ thông tin bắt buộc');
    });
  };

  // Đăng bài viết
  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);
      
      message.loading('Đang tạo bài viết...', 0);
      
      const article = {
        title: values.title,
        content: values.content,
        category: categories[values.category] || values.category,
        source: values.source || 'Admin tạo thủ công',
        imageUrl: values.imageUrl || null,
        url: values.url || null,
        publishedAt: values.publishedAt ? values.publishedAt.toDate() : new Date(),
        scrapedAt: new Date(),
        isAutoGenerated: false // Đánh dấu là tạo thủ công
      };
      
      await createPost(article);
      
      message.destroy();
      message.success('Đã tạo bài viết thành công!');
      
      // Reset form
      form.resetFields();
      setImageUrl('');
      setPreviewData(null);
      
    } catch (error) {
      message.destroy();
      message.error('Lỗi khi tạo bài viết: ' + error.message);
      console.error('Create post error:', error);
    } finally {
      setLoading(false);
    }
  };

  // Format thời gian
  const formatDate = (date) => {
    return new Date(date).toLocaleString('vi-VN', {
      day: '2-digit',
      month: '2-digit', 
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <div className="space-y-6">
      <Card>
        <Title level={3} className="flex items-center gap-2 text-[#795548]">
          <EditOutlined />
          Tạo bài viết thủ công
        </Title>
        


        <Form
          form={form}
          layout="vertical"
          initialValues={{
            category: 'nong-nghiep',
            source: 'Khuyến nông',
            publishedAt: moment()
          }}
        >
          <Row gutter={16}>
            <Col xs={24} lg={16}>
              <Form.Item
                label="Tiêu đề bài viết"
                name="title"
                rules={[{ required: true, message: 'Vui lòng nhập tiêu đề!' }]}
              >
                <Input placeholder="Nhập tiêu đề bài viết..." />
              </Form.Item>

              <Form.Item
                label="Nội dung"
                name="content"
                rules={[{ required: true, message: 'Vui lòng nhập nội dung!' }]}
              >
                <TextArea 
                  rows={6} 
                  placeholder="Nhập nội dung bài viết..."
                  showCount
                  maxLength={2000}
                />
              </Form.Item>

              <Row gutter={16}>
                <Col xs={24} sm={12}>
                  <Form.Item
                    label="Danh mục"
                    name="category"
                    rules={[{ required: true, message: 'Vui lòng chọn danh mục!' }]}
                  >
                    <Select placeholder="Chọn danh mục">
                      {Object.entries(categories).map(([key, name]) => (
                        <Option key={key} value={key}>{name}</Option>
                      ))}
                    </Select>
                  </Form.Item>
                </Col>
                <Col xs={24} sm={12}>
                  <Form.Item
                    label="Nguồn"
                    name="source"
                  >
                    <Input placeholder="Nguồn bài viết" />
                  </Form.Item>
                </Col>
              </Row>

              <Row gutter={16}>
                <Col xs={24} sm={12}>
                  <Form.Item
                    label="Thời gian đăng"
                    name="publishedAt"
                  >
                    <DatePicker 
                      showTime 
                      format="DD/MM/YYYY HH:mm"
                      placeholder="Chọn thời gian"
                      style={{ width: '100%' }}
                    />
                  </Form.Item>
                </Col>
                <Col xs={24} sm={12}>
                  <Form.Item
                    label="Link gốc (tùy chọn)"
                    name="url"
                  >
                    <Input placeholder="https://..." />
                  </Form.Item>
                </Col>
              </Row>
            </Col>

            <Col xs={24} lg={8}>
              <Form.Item label="Hình ảnh">
                <Space direction="vertical" className="w-full">
                  <Form.Item name="imageUrl" noStyle>
                    <Input 
                      placeholder="Nhập URL hình ảnh..."
                      onChange={handleImageUrlChange}
                    />
                  </Form.Item>
                  
                  <Upload
                    name="image"
                    listType="picture-card"
                    className="avatar-uploader"
                    showUploadList={false}
                    beforeUpload={() => false}
                    onChange={handleImageChange}
                  >
                    {imageUrl ? (
                      <Image
                        src={imageUrl}
                        alt="preview"
                        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                      />
                    ) : (
                      <div>
                        <PlusOutlined />
                        <div style={{ marginTop: 8 }}>Upload</div>
                      </div>
                    )}
                  </Upload>
                </Space>
              </Form.Item>
            </Col>
          </Row>

          <div style={{ marginTop: '24px', display: 'flex', gap: '12px' }}>
            <Button 
              type="default" 
              icon={<EyeOutlined />}
              onClick={handlePreview}
              size="large"
              style={{ display: 'inline-flex', alignItems: 'center' }}
            >
              Xem trước
            </Button>
            <Button 
              type="primary" 
              icon={<SendOutlined />}
              onClick={handleSubmit}
              loading={loading}
              size="large"
              style={{ 
                backgroundColor: '#795548', 
                borderColor: '#795548',
                display: 'inline-flex', 
                alignItems: 'center'
              }}
            >
              Đăng bài viết
            </Button>
          </div>
        </Form>
      </Card>

      {/* Preview bài viết */}
      {previewData && (
        <Card title="Xem trước bài viết">
          <div className="border rounded-lg p-4 bg-gray-50">
            <div className="flex items-center gap-2 mb-2">
              <Text strong className="text-lg">
                {previewData.title}
              </Text>
            </div>
            
            <Space className="mb-3">
              <span className="flex items-center gap-1 text-sm text-gray-500">
                <CalendarOutlined />
                {formatDate(previewData.publishedAt)}
              </span>
              <Tag color="blue">{previewData.category}</Tag>
              <Tag color="green">{previewData.source}</Tag>
            </Space>

            {previewData.imageUrl && (
              <div className="mb-3">
                <Image
                  width={200}
                  src={previewData.imageUrl}
                  alt={previewData.title}
                />
              </div>
            )}
            
            <Paragraph className="text-gray-700">
              {previewData.content}
            </Paragraph>

            {previewData.url && (
              <div className="mt-2">
                <Button 
                  type="link" 
                  icon={<LinkOutlined />}
                  href={previewData.url}
                  target="_blank"
                >
                  Xem bài gốc
                </Button>
              </div>
            )}
          </div>
        </Card>
      )}
    </div>
  );
};

export default AdminPostCreator;