import React, { useState, useCallback, useEffect } from 'react';
import { doc, updateDoc, increment, setDoc, deleteDoc, onSnapshot } from 'firebase/firestore';
import { db } from '../firebase/config';
import { useAuth } from '../hooks/useAuth';
import { useAuthGuard } from '../hooks/useAuthGuard';
import { createNotification, notificationTypes } from '../services/notificationService';
import { logUserAction, ACTIONS } from '../utils/analytics';
import ImageGallery from './ImageGallery';
import CommentSection from './CommentSection';
import ShareDialog from './ShareDialog';
import PostMenu from './PostMenu';
import SaveButton from './SaveButton';
import ReactionButton from './ReactionButton';
import LoginModal from './common/LoginModal';
import { useNavigate } from 'react-router-dom';
import moment from 'moment';
import { MessageCircle, Share2, MoreHorizontal } from 'lucide-react';
import OptimizedImage from './OptimizedImage';

const PostCard = ({ post, isDetailView = false }) => {
  const { user, userProfile, updateReputation } = useAuth();
  const { requireAuthForLike, requireAuthForComment, showLoginModal, setShowLoginModal } = useAuthGuard();
  const navigate = useNavigate();
  const [userReaction, setUserReaction] = useState(null);
  
  // Load user's like status
  useEffect(() => {
    if (!user || !post.id) return;
    
    const likeDoc = doc(db, 'likes', `${user.uid}_${post.id}`);
    const unsubscribe = onSnapshot(likeDoc, (doc) => {
      setUserReaction(doc.exists() ? 'like' : null);
    });
    
    return unsubscribe;
  }, [user, post.id]);
  const [showComments, setShowComments] = useState(false);
  const [commentCount, setCommentCount] = useState(post.comments || 0);
  const [showShareDialog, setShowShareDialog] = useState(false);
  const [showFullContent, setShowFullContent] = useState(false);
  const [menuAnchor, setMenuAnchor] = useState(null);
  
  const contentLimit = 200;
  const shouldTruncate = post.content.length > contentLimit;

  const handleReaction = useCallback(async (reactionType) => {
    return requireAuthForLike(async () => {
      const wasLiked = userReaction === 'like';
      const willLike = reactionType === 'like';
      
      try {
        const likeDoc = doc(db, 'likes', `${user.uid}_${post.id}`);
        
        if (wasLiked) {
          // Unlike
          await deleteDoc(likeDoc);
          await updateDoc(doc(db, 'posts', post.id), {
            likes: increment(-1)
          });
        } else if (willLike) {
          // Like
          await setDoc(likeDoc, {
            userId: user.uid,
            postId: post.id,
            createdAt: new Date()
          });
          await updateDoc(doc(db, 'posts', post.id), {
            likes: increment(1)
          });
          await logUserAction(user.uid, userProfile?.displayName || user.email, ACTIONS.LIKE_POST, { postId: post.id, postAuthor: post.authorName });
          
          if (post.authorId !== user.uid) {
            await updateReputation(post.authorId, 1);
            await createNotification(
              post.authorId,
              notificationTypes.LIKE,
              `${userProfile?.displayName || user.email} đã thích bài viết: "${post.title}"`,
              post.id
            );
          }
        }
      } catch (error) {
        console.error('Error updating like:', error);
      }
    });
  }, [user, post.id, post.authorId, updateReputation, userProfile, userReaction, requireAuthForLike]);

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden font-sans">

      {/* Post Header */}
      <div className="p-4">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-3">
            <OptimizedImage
              src={post.authorAvatar || `https://ui-avatars.com/api/?name=${post.authorName}&background=4CAF50&color=fff`}
              alt={post.authorName}
              width={40}
              height={40}
              className="w-10 h-10 rounded-full object-cover border border-gray-200 cursor-pointer hover:ring-2 hover:ring-[#4CAF50] transition-all"
              onClick={() => navigate(`/user/${post.authorId}`)}
            />
            <div>
              <h4 
                className="font-bold text-gray-900 text-sm cursor-pointer hover:text-[#4CAF50] transition-colors leading-tight flex items-center gap-1"
                onClick={() => navigate(`/user/${post.authorId}`)}
              >
                {post.authorName}
                {post.isAutoGenerated && (
                  <svg className="w-4 h-4 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                  </svg>
                )}
              </h4>
              <div className="flex items-center gap-2 text-xs text-gray-500 leading-tight">
                <span>{moment(post.createdAt instanceof Date ? post.createdAt : post.createdAt?.toDate?.() || new Date()).fromNow()}</span>
                <span className="w-1 h-1 bg-gray-300 rounded-full"></span>
                <span className={`px-2 py-0.5 rounded-full font-medium ${post.authorReputation >= 100 ? 'bg-blue-100 text-blue-700' : 'bg-green-100 text-green-700'}`}>
                  {post.authorReputation >= 100 ? 'Chuyên gia' : 'Nông dân'}
                </span>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <SaveButton postId={post.id} />
            <button 
              onClick={(e) => setMenuAnchor(e.currentTarget)}
              aria-label="Tùy chọn bài viết"
              className="p-1.5 hover:bg-gray-100 rounded-full transition-colors"
            >
              <MoreHorizontal className="w-4 h-4 text-gray-500" />
            </button>
          </div>
        </div>
        
        {/* Post Content */}
        {post.title && (
          <h3 className="text-lg font-bold text-gray-800 mb-2 leading-tight">
            {post.title}
          </h3>
        )}
        <p className="text-gray-600 mb-4 whitespace-pre-wrap leading-relaxed">
          {shouldTruncate && !showFullContent 
            ? post.content.substring(0, contentLimit) + '...' 
            : post.content}
          {shouldTruncate && (
            <button 
              onClick={() => setShowFullContent(!showFullContent)}
              className="ml-1 text-[#4CAF50] hover:text-[#45a049] font-medium text-sm"
            >
              {showFullContent ? 'Thu gọn' : 'Xem thêm'}
            </button>
          )}
        </p>
        
        {/* Post Images */}
        {((post.images && post.images.length > 0) || post.imageUrl) && (
          <div className="mb-4 rounded-lg overflow-hidden">
            {post.images && post.images.length > 0 ? (
              <ImageGallery images={post.images} />
            ) : post.imageUrl ? (
              <OptimizedImage
                src={post.imageUrl}
                alt={post.title}
                width={600}
                height={300}
                className="w-full h-64 object-cover rounded-lg"
              />
            ) : null}
          </div>
        )}

        {/* Source Link */}
        {post.url && (
          <div className="mb-3">
            <a 
              href={post.url}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm text-blue-600 hover:text-blue-800 font-medium transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
              </svg>
              Đọc bài gốc tại {post.source || 'nguồn'}
            </a>
          </div>
        )}

        {/* Category Tags */}
        {post.category && (
          <div className="flex flex-wrap gap-2 mb-4">
            <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded-md font-medium">#{post.category}</span>
            {post.source && (
              <span className="text-xs bg-blue-100 text-blue-600 px-2 py-1 rounded-md font-medium">{post.source}</span>
            )}
          </div>
        )}

        {/* Post Actions */}
        <div className="flex items-center justify-between border-t border-gray-100 pt-3">
          <div className="flex gap-4">
            <ReactionButton
              onReaction={handleReaction}
              currentReaction={userReaction}
              totalLikes={post.likes || 0}
            />
            <button 
              onClick={() => requireAuthForComment(() => setShowComments(!showComments))}
              aria-label={showComments ? "Ẩn bình luận" : "Hiển thị bình luận"}
              className="flex items-center gap-1 text-gray-500 hover:text-blue-500 transition-colors text-sm font-medium"
            >
              <MessageCircle className="w-5 h-5" />
              {commentCount > 0 && commentCount}
            </button>
            <button 
              onClick={() => setShowShareDialog(true)}
              aria-label="Chia sẻ bài viết"
              className="flex items-center gap-1 text-gray-500 hover:text-green-500 transition-colors text-sm font-medium"
            >
              <Share2 className="w-5 h-5" />
            </button>
          </div>
          {!isDetailView && (
            <button
              onClick={() => {
                logUserAction(user?.uid, userProfile?.displayName || user?.email, ACTIONS.VIEW_POST, { postId: post.id, postTitle: post.title });
                navigate(`/post/${post.id}`);
              }}
              className="text-xs text-gray-500 hover:text-[#4CAF50] transition-colors font-medium"
            >
              Chi tiết
            </button>
          )}
        </div>
      </div>
      
      {/* Comments Section */}
      {showComments && (
        <div className="bg-gray-50 p-4 border-t border-gray-100 space-y-4">
          <CommentSection 
            postId={post.id}
            postAuthorId={post.authorId}
            postContent={post.content}
            postTitle={post.title}
            onCommentCountChange={setCommentCount}
          />
        </div>
      )}
      
      <ShareDialog 
        open={showShareDialog}
        onClose={() => setShowShareDialog(false)}
        post={post}
      />
      
      <PostMenu
        anchorEl={menuAnchor}
        open={Boolean(menuAnchor)}
        onClose={() => setMenuAnchor(null)}
        post={post}
        currentUser={user}
        onPostUpdated={() => window.location.reload()}
        onPostDeleted={() => window.location.reload()}
      />

      {/* Login Modal */}
      <LoginModal 
        isOpen={showLoginModal}
        onClose={() => setShowLoginModal(false)}
        message="Đăng nhập để tương tác với bài viết"
        feature="thích và bình luận bài viết"
      />
    </div>
  );
};

export default React.memo(PostCard);